### ISSUE TITLE
Button.tsx | Typescript error on <button> anchor tag

### ISSUE THREAD

**Issue by tonoli** [duncanleung/gatsby-typescript-emotion-storybook#107]
In the `src/components/Button/Button.tsx ` There is an error typescript I'm unable to mute. 

Do you have an idea how to solve this? 

![Screen Shot 2020-03-19 at 15 15 33](https://user-images.githubusercontent.com/17257576/77076737-85720400-69f4-11ea-908f-a99a8d7bb5c0.png)

**Comment by duncanleung** [comment]
@tonoli Sorry for the delay.

I think I have a fix - should be up by this evening.
